---
- hosts: all
  become: yes
  vars:
    arch_mapping:
      x86_64: amd64
      aarch64: arm64
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        state: latest
        upgrade: dist

    - name: Install required software
      apt:
        name:
          - git
          - curl
          - nginx
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Create the /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to apt sources
      copy:
        content: |
          deb [arch={{ arch_mapping[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        dest: /etc/apt/sources.list.d/docker.list

    - name: Update apt package index again
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
